"""Smoke tests for the crazypumpkin CLI install and init flow."""

import subprocess
import sys
from pathlib import Path
from unittest.mock import patch

import pytest
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from crazypumpkin.cli import _write_init_files, cmd_init, main


def test_help_exits_zero_and_contains_prog_name():
    """'crazypumpkin --help' exits 0 and output contains 'crazypumpkin'."""
    src_dir = str(Path(__file__).resolve().parent.parent / "src")
    import os
    env = os.environ.copy()
    env["PYTHONPATH"] = src_dir + os.pathsep + env.get("PYTHONPATH", "")
    result = subprocess.run(
        [sys.executable, "-m", "crazypumpkin.cli", "--help"],
        capture_output=True,
        text=True,
        env=env,
    )
    assert result.returncode == 0
    assert "crazypumpkin" in result.stdout


def test_cmd_init_creates_config_yaml(tmp_path):
    """cmd_init() in tmp_path creates config.yaml."""
    import argparse
    import io
    from contextlib import redirect_stdout

    examples_dir = tmp_path / "_examples"
    examples_dir.mkdir(exist_ok=True)
    default_json = examples_dir / "default.json"
    default_json.write_text("{}", encoding="utf-8")

    args = argparse.Namespace(command="init", force=True)
    inputs = iter(["Test Corp", "anthropic_api", "sk-test", "/tmp/product", "pass"])
    with patch("builtins.input", side_effect=inputs), \
         patch("crazypumpkin.cli.Path") as mock_path, \
         patch("crazypumpkin.cli._get_default_json_path", return_value=default_json):
        mock_path.cwd.return_value = tmp_path
        mock_path.side_effect = Path
        with redirect_stdout(io.StringIO()):
            cmd_init(args)

    assert (tmp_path / "config.yaml").exists()


def test_cmd_init_config_yaml_has_expected_top_level_keys(tmp_path):
    """config.yaml generated by cmd_init contains all expected top-level keys."""
    import argparse
    import io
    from contextlib import redirect_stdout

    examples_dir = tmp_path / "_examples"
    examples_dir.mkdir(exist_ok=True)
    default_json = examples_dir / "default.json"
    default_json.write_text("{}", encoding="utf-8")

    args = argparse.Namespace(command="init", force=True)
    inputs = iter(["Test Corp", "anthropic_api", "sk-test", "/tmp/product", "pass"])
    with patch("builtins.input", side_effect=inputs), \
         patch("crazypumpkin.cli.Path") as mock_path, \
         patch("crazypumpkin.cli._get_default_json_path", return_value=default_json):
        mock_path.cwd.return_value = tmp_path
        mock_path.side_effect = Path
        with redirect_stdout(io.StringIO()):
            cmd_init(args)

    config_text = (tmp_path / "config.yaml").read_text(encoding="utf-8")
    cfg = yaml.safe_load(config_text)
    for key in ("company", "products", "llm", "agents", "pipeline", "notifications", "dashboard", "voice"):
        assert key in cfg, f"Missing top-level key: {key}"


def test_cmd_init_config_yaml_is_valid_yaml(tmp_path):
    """config.yaml generated by cmd_init is valid YAML."""
    import argparse
    import io
    from contextlib import redirect_stdout

    examples_dir = tmp_path / "_examples"
    examples_dir.mkdir(exist_ok=True)
    default_json = examples_dir / "default.json"
    default_json.write_text("{}", encoding="utf-8")

    args = argparse.Namespace(command="init", force=True)
    inputs = iter(["Test Corp", "anthropic_api", "sk-test", "/tmp/product", "pass"])
    with patch("builtins.input", side_effect=inputs), \
         patch("crazypumpkin.cli.Path") as mock_path, \
         patch("crazypumpkin.cli._get_default_json_path", return_value=default_json):
        mock_path.cwd.return_value = tmp_path
        mock_path.side_effect = Path
        with redirect_stdout(io.StringIO()):
            cmd_init(args)

    config_text = (tmp_path / "config.yaml").read_text(encoding="utf-8")
    parsed = yaml.safe_load(config_text)
    assert isinstance(parsed, dict)
